import { useState, createContext, useContext, useEffect, useCallback } from "react"
import toast, { Toaster } from 'react-hot-toast';
import dayjs from 'dayjs';


const GeneralSettingsContext = createContext(null)


const ApplicationSettings = ({children}) => {

    const initialValue = {
        check_update_username: false,
        check_update_password: false,
        prefix: '',
        minimum_digits: '',
        welcome_back_message: false,
        router_name: '',
        use_radius: false
    
      }


      const initialValueAdminSettings = {
        enable_2fa_for_admin_email: false,
        enable_2fa_for_admin_sms: false,
        enable_2fa_google_auth: false,
        send_password_via_sms: false,
        send_password_via_email: false,
        enable_2fa_for_admin_passkeys: false,
        check_is_inactive: false,
        checkinactiveminutes: '',
        checkinactivehrs: '',
        checkinactivedays: ''
      }


      const nasSettings = {
        notification_when_unreachable: false,
        unreachable_duration_minutes: '',
        notification_phone_number: ''
      }


 const accessPointSettings = {
        notification_when_unreachable: false,
        unreachable_duration_minutes: '',
        notification_phone_number: ''
      }


      const initialValueNas = {
        username:'',
        password: '',
        ip_address:'',
        name: '',
        location: '',
        }


        const initialValueAccessPoint = {
        
        ip:'',
        name: '',
        location: '',
        longitude: '',
        latitude: '',
        }
        const subscriber_settings = {
          prefix: '',
          minimum_digits: '',
          use_autogenerated_number_as_ppoe_username: false,
          use_autogenerated_number_as_ppoe_password: false,
          notify_user_account_created: false,
          send_reminder_sms_expiring_subscriptions: false,
          account_number_starting_value: 0,
          enable_customer_portal: false,
          installation_fee: 0,
          send_welcome_message: false,
          subscriber_welcome_message: false,
          lock_account_to_mac: false,
          notify_user_payment_received: false,
          invoice_created_or_paid: false,
          expiration_reminder: false,
          expiration_reminder_minutes: '',
          expiration_reminder_hours: '',
          expiration_reminder_days: '',


        }
        const [walletBalance, setWalletBalance] = useState('0')

      const [settingsformData, setFormData]= useState(initialValue)
      const [nasSettingsForm, setNasSettingsForm] = useState(nasSettings)

      const [expiry, setExpiry] = useState('No license')
const [expiry2, setExpiry2] = useState('No license')
const [condition, setCondition] = useState(false)
const [condition2, setCondition2] = useState(false)
const [status, setStatus] = useState('Not Active')
const [status2, setStatus2] = useState('Not Active')
const [currentHotspotPlan, setCurrentHotspotPlan] = useState(null)
const [currentPPOEPlan, setCurrentPPOEPlan] = useState(null)
const [accessPointForm, setAccessPointForm] = useState(initialValueAccessPoint)
const [accessPointSettingsForm, setAccessPointSettingsForm] = useState(accessPointSettings)




  const intialValueSubscriber = {
    name: '',
    latitude: '',
    longitude: '',
    house_number: '',
    building_name: '',
    phone_number: '',
    ppoe_username: '',
    // ppoe_password: '',
    ref_no: '',
    network_name: '',
    validity: '',
    validity_period_units: '',
    
  
    ip_address: '',
    package_name: '',
    installation_fee: '',
    subscriber_discount: '',
    second_phone_number: '',
    node: '',
    location: '',
    date_registered: dayjs(),
    email: '',
    router_name: '',
    check_update_username: settingsformData.check_update_username,
    check_update_password: settingsformData.check_update_password
    

  }
  const [hotspotCustomization, setHotspotCustomization] = useState({
    customize_template_and_package_per_location: false,
    enable_autologin: false,
    compensation_hours: '',
    compensation_minutes: '',
    enable_compensation: false

  })


const [formDataSubscriber, setFormDataSubscriber] = useState(intialValueSubscriber)

        const  [nasformData, setnasFormData] = useState(initialValueNas)
        const [welcomeMessage, setWelcomeMessage] =  useState('')
const [welcome, setWelcome] = useState(false)
      const [tableDataNas, setTableData] = useState([])
      const [currentUser, setCurrentUser] = useState('')
      const [currentEmail, setCurentEmail] = useState('')
      const [currentSystemAdmin, setCurrentSystemAdmin] = useState('')
      const [currentUsername, setCurrentUsername] = useState('')
      const [subscriberSettings, setSubscriberSettings] = useState(subscriber_settings)
      let [adminSettings, setAdminSettings] = useState(initialValueAdminSettings)
      const [companySettings, setCompanySettings] = useState({
        company_name: '',
  contact_info: '',
  email_info: '',
  logo: null, 
  logo_preview: null ,
  agent_email: '',
  customer_support_email: '',
  customer_support_phone_number: '',
  location: '',

      })


const [voucher, setVoucher] = useState({
  vouchers: ''
})

const [smsBalance, setSmsBalance] = useState(0)

const [smsSettingsForm, setSmsSettingsForm] = useState({
  api_key: '',
  api_secret: '',
  sender_id: '',
  short_code: '',
  partnerID: '',

   username: '',
});


const [hotspotMpesaSettings, setHotspotMpesaSettings] = useState({
  shortcode: '',
  consumer_secret: '',
  consumer_key: '',
  passkey: '',
  api_initiator_username: '',
  api_initiator_password: '',
  phone_number: '',
  
});


const [dialMpesaSettings, setDialMpesaSettings] = useState({
  consumer_secret: '',
  consumer_key: '',
  short_code: '',
  
});


const [loading, setLoading] = useState(false)
 const [success, setsuccess] = useState(false)
const [totalSubscribers, setTotalSubscribers] = useState(0)
const [subscribersOnline, setSubscribersOnline] = useState(0)
const [subscribersOffline, setSubscribersOffline] = useState(0)
const [openDropDown, setOpenDropDown] = useState(false)

const [pingStatus, setPingStatus] = useState([]); 

const {vouchers} = voucher

const [showMenu1, setShowMenu1] = useState(false);

const [showMenu2, setShowMenu2] = useState(false);

const [showMenu3, setShowMenu3] = useState(false);

const [showMenu4, setShowMenu4] = useState(false);

const [showMenu5, setShowMenu5] = useState(false);

const [showMenu6, setShowMenu6] = useState(false);
const [showMenu7, setShowMenu7] = useState(false);
const [showMenu8, setShowMenu8] = useState(false);
const [showMenu9, setShowMenu9] = useState(false);

const [showMenu10, setShowMenu10] = useState(false);
const [showMenu11, setShowMenu11] = useState(false);
const [showMenu12, setShowMenu12] = useState(false);
// const { vouchers } = voucher
const handleChangeHotspotVoucher = (e) => {
  const { value, name } = e.target;
  setVoucher((prevData) => ({
    ...prevData,
    [name]: value
  }))
}


function calculateTimeRemaining(expiryDateString) {
    // Parse the expiry date (format: "June 07, 2025 at 05:12 PM")
    const expiryDate = new Date(expiryDateString?.replace(' at ', ' '));
    const now = new Date();
    const diffMs = expiryDate - now;
    
    // If already expired
    if (diffMs <= 0) return '(license expired)';
  
    // Calculate time components
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
    const diffHours = Math.floor((diffMs % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    const diffMinutes = Math.floor((diffMs % (1000 * 60 * 60)) / (1000 * 60));
  
    // Build human-readable string
    let result = '';
    if (diffDays > 0) {
      const weeks = Math.floor(diffDays / 7);
      const days = diffDays % 7;
      
      if (weeks > 0) result += `${weeks} week${weeks !== 1 ? 's' : ''} `;
      if (days > 0) result += `${days} day${days !== 1 ? 's' : ''} `;
    }
    
    if (diffHours > 0 && diffDays < 2) {
      result += `${diffHours} hour${diffHours !== 1 ? 's' : ''} `;
    }
    
    if (diffMinutes > 0 && diffDays === 0) {
      result += `${diffMinutes} minute${diffMinutes !== 1 ? 's' : ''}`;
    }
  
    // If less than 1 minute remains
    if (result === '') return 'expires in less than 1 minute';
  
    return `expires in ${result?.trim()}`;
  }


      const [formData, setFormDataSystemAdmin] = useState({
        password: '',
        phone_number: '',
        email: ''
      })
      const [templateStates, setTemplateStates] = useState({
        clean: false,
        default_template: false,
        sleekspot: false,
        attractive: false,
        flat: false,
        minimal: false,
        simple: false,
        default: false,
        sleek: false, 
        location: ''
      });

      const [selectedProvider, setSelectedProvider] = useState('SMS leopard'); // Default value
      const [selectedAccountTypeHotspot, setSelectedAccountTypeHotspot] = useState('Till'); // Default value
      const [selectedAccountTypeSubscriber, setSelectedAccountTypeSubscriber] = useState('Paybill'); // Default value

      // const [settingsformData, setFormData] = useState(() => {
      //   const storedFormData =   localStorage.setItem("checkedtrueData", JSON.stringify(initialValue.check_update_password));
        
      //   return storedFormData ? JSON.parse(storedFormData) : initialValue;
      // });


      const [phoneNumber, setPhoneNumber] = useState("");
      const [email, setEmail] = useState("");
      const [hotspotName, setHotspotName] = useState("");
      const [hotspotInfo, setHotspotInfo] = useState("");
      const [hotspotBanner, setHotspotBanner] = useState(null);
      const [hotspotBannerPreview, setHotspotBannerPreview] = useState(null); 
      const [locationInput, setLocationInput] = useState('');
    const [allLocations, setAllLocations] = useState([
        'Nairobi',
        'Mombasa',
        'Kisumu',
        'Eldoret',
        'Nakuru',
        'Thika',
        'Malindi',
        'Kitale',
        'Kakamega',
        'Kisii'
    ]);

    const [formDataGeneralSettings, setFormDataGeneralSettings] = useState({
      title: '',
      timezone: '',
      allowed_ips: '',
    });

const [currentCustomer, setCurrentCustomer] = useState(null)
const [routerName, setRouterName] = useState(null)
const [openRouterDetails, setOpenRouterDetails] = useState(false)
const [openNasTable, setOpenNasTable] = useState(true)




const handleChangeHotspotCustomization = (e) => {
  const { type, name, checked, value } = e.target;
  // setHotspotCustomization((prevFormData) => ({

  //      ...prevFormData,
  //   [name]: type === "checkbox" ? checked : value,
  // }));



  setHotspotCustomization((prevData) => {
          let updatedSettings = { ...prevData, [name]: type === "checkbox" ? checked : value, };
      
     
          if (name === 'compensation_minutes') {
     
        updatedSettings.compensation_hours = ''
      
          }else if (name === 'compensation_hours'){

            updatedSettings.compensation_minutes = ''

          }
      
         
          return updatedSettings;

        });      
};




const handleChangeNasSettings = (e) => {
  const { type, name, checked, value } = e.target;
  setNasSettingsForm((prevFormData) => ({
    ...prevFormData,
    [name]: type === "checkbox" ? checked : value,
  }));
};

const handleChanageAccessPointSettings = (e) => {
  const { type, name, checked, value } = e.target;
  setAccessPointSettingsForm((prevFormData) => ({
    ...prevFormData,
    [name]: type === "checkbox" ? checked : value,
  }));

}


      const handleChangeSubscriberSettings = (e) => {
        const { type, name, checked, value } = e.target;

        // const capitalizedName = value.toUpperCase() 
        // setSubscriberSettings((prevFormData) => ({
        //   ...prevFormData,
        //   [name]: type === "checkbox" ? checked : capitalizedName,

        // }));


const capitalizedName = value.toUpperCase() 
  setSubscriberSettings((prevData) => {
          let updatedData = { ...prevData };
          let updatedSettings = { ...prevData, [name]: type === "checkbox" ? checked : capitalizedName, };
      
     
          if (name === 'expiration_reminder_minutes') {
     
        updatedSettings.expiration_reminder_hours = ''
            updatedSettings.expiration_reminder_days = ''
      
          } else if (name === 'expiration_reminder_hours'){

            updatedSettings.expiration_reminder_minutes = ''
            updatedSettings.expiration_reminder_days = ''
          }else if (name === 'expiration_reminder_days'){

            updatedSettings.expiration_reminder_minutes = ''
            updatedSettings.expiration_reminder_hours = ''

          }
      
         
          return updatedSettings;

        });        

      }

      const handleChangeAdminSettings = (e) => {
        const { type, name, checked, value } = e.target;
       
  
        setAdminSettings((prevData) => {
          let updatedData = { ...prevData };
          let updatedSettings = { ...prevData, [name]: type === "checkbox" ? checked : value, };
      
     
          if (name === 'enable_2fa_for_admin_sms') {

 if (updatedSettings.enable_2fa_for_admin_sms) {
    updatedSettings.enable_2fa_for_admin_email = false;
    updatedSettings.enable_2fa_for_admin_passkeys = false;
    updatedSettings.enable_2fa_google_auth = false;
  }
           
      
      
          } else if (name === 'enable_2fa_for_admin_email') {
             if (updatedSettings.enable_2fa_for_admin_email) {
               updatedSettings.enable_2fa_for_admin_sms = false
              updatedSettings.enable_2fa_for_admin_passkeys = false
              updatedSettings.enable_2fa_google_auth = false
      
             }
             
      
          
            
          } else if (name === 'enable_2fa_for_admin_passkeys') {

            if (updatedSettings.enable_2fa_for_admin_passkeys) {
               updatedSettings.enable_2fa_google_auth = false
              updatedSettings.enable_2fa_for_admin_sms = false
              updatedSettings.enable_2fa_for_admin_email = false
            
            }
               
             
          }else if (name === 'enable_2fa_google_auth'){
            if ( updatedSettings.enable_2fa_google_auth) {
               updatedSettings.enable_2fa_for_admin_passkeys = false
            updatedSettings.enable_2fa_for_admin_email = false
            updatedSettings.enable_2fa_for_admin_sms = false

            }
           

            
            
          
          }else if (name === 'login_with_otp_email'){
            updatedSettings.enable_2fa_for_admin = true
          
          }else if (name === 'checkinactiveminutes'){

            updatedSettings.checkinactivehrs = ''
            updatedSettings.checkinactivedays = ''

          }else if (name === 'checkinactivehrs'){

            updatedSettings.checkinactiveminutes = ''
            updatedSettings.checkinactivedays = ''
          }else if (name === 'checkinactivedays'){

            updatedSettings.checkinactiveminutes = ''
            updatedSettings.checkinactivehrs = ''

          }
      
         
          return updatedSettings;

        });

        
      }

    const [isloading, setisloading] = useState(false)
    
const [loginWithPasskey, setLoginWithPasskey] = useState(false)
const [useEmailAuthentication, setUseEmailAuthentication] = useState(false)
const [usePhoneNumberAuthentication, setUsePhoneNumberAuthentication] = useState(false)
const [providerSms, setProviderSms] = useState(false)
const [hotspotPhoneNumber, setHotspotPhoneNumber] = useState('')
const [hotspotEmail, setHotspotEmail] = useState('')

//   const handleChange = (e) => {
//     const {type, name, checked, value} = e.target
//  setFormData({...settingsformData, [name]:  type === 'checkbox'  ? checked :  value  })
 
 
//    }

const subdomain = window.location.hostname.split('.')[0];
const fetchSubscriberUpdatedSettings = useCallback(async () => {
  const storedData = JSON.parse(localStorage.getItem("checkedtrueData2"));

const requestParams = {
check_update_password:storedData.check_update_password ,
check_update_username: storedData.check_update_username,
welcome_back_message: storedData.welcome_back_message,
router_name: storedData.router_name
};

try {
const response = await fetch(`/api/get_general_settings?${new URLSearchParams(requestParams)}`, {
method: 'GET',
headers: {
  "Content-Type"  : 'application/json',
  'X-Subdomain': subdomain,
},


})
const newData = await response.json()
if (response.ok) {

// const check_password =  checkedData.check_update_password
// const check_username = checkedData.check_update_username
// console.log('check username', check_username)
// const welcome_back_message = storedData.welcome_back_message

const {prefix, minimum_digits, check_update_password, check_update_username,
  welcome_back_message, router_name} = newData[0]
setFormData({...settingsformData, prefix,  minimum_digits, check_update_password, check_update_username, 
   welcome_back_message,
router_name
})

} else {
}
} catch (error) {

}
}, []) 





const fetchCurrentUser = useCallback(
  async() => {
    // document.title = subdomain

    try {
      const response = await fetch('/api/currently_logged_in_user', {
        headers: {
          'X-Subdomain': subdomain,
        },
      })
      const newData = await response.json()
      if (response) {
        const {username, email, id, created_at, updated_at} = newData
        setCurrentUser(newData)
        setCurrentUsername(username)
        setCurentEmail(email)
      }else{
        setCurrentUser(null) 
      }
    } catch (error) {
      setCurrentUser(null) 
    }
  },
  [],
)



useEffect(() => {
  fetchCurrentUser()
}, [fetchCurrentUser]);












const fetchCurrentSystemAdmin = useCallback(
  async() => {
    try {
      const response = await fetch('/api/current_system_admin', {
        headers: {
          'X-Subdomain': subdomain,
        },
      })
      const newData = await response.json()
      if (response) {
        const {user_name, email, id, created_at, updated_at, phone_number} = newData
        setCurrentSystemAdmin(newData)
      }
    } catch (error) {
    }
  },
  [],
)



useEffect(() => {
  fetchCurrentSystemAdmin()
}, [fetchCurrentSystemAdmin]);


const [customerProfileData, setCustomerProfileData] = useState(null);



const fetchCurrentCustomer = useCallback(
  async() => {
    try {
      const response = await fetch('/api/current_customer', {
        headers: {
          'X-Subdomain': subdomain,
        },
      })
      const newData = await response.json()
      if (response) {
        // const {user_name, email, id, created_at, updated_at, phone_number} = newData
        setCurrentCustomer(newData)
        setCustomerProfileData(newData)
      }
    } catch (error) {
    }
  },
  [],
)



useEffect(() => {
  fetchCurrentCustomer()
}, [fetchCurrentCustomer]);


useEffect(() => {
  const fetchRouters =  async() => {


    try {
      const response = await fetch('/api/router_settings', {
        headers: {
          'X-Subdomain': subdomain,
        },
      })
const newData = await response.json()
      if (response) {
        const {router_name} = newData[0]
        setFormData({...settingsformData, router_name})
      } else {
        // console.log('failed to fetch router settings')
      }
    } catch (error) {
      // console.log(error)
    }
  }
  fetchRouters()
}, []);












 useEffect(() => {
  
  fetchSubscriberUpdatedSettings()
 }, [fetchSubscriberUpdatedSettings, setFormData]);






const handleChange = (e) => {
  const { type, name, checked, value } = e.target;
  setFormData((prevFormData) => ({
    ...prevFormData,
    [name]: type === "checkbox" ? checked : value,
  }));
};


// const fetchCurrentUser = async() => {
//   try {
//     const response = await fetch('/api/currently_logged_in_user')
//     const newData = await response.json()
//     if (response) {
//       console.log('fetched current user', newData)
//       const {username, email} = newData
//       setCurrentUser(newData)
//       setCurrentUsername(username)
//       setCurentEmail(email)
//       console.log('current user', newData)
//     }
//   } catch (error) {
    
//   }
//  }


 
const storedIp = localStorage.getItem('hotspot_mac')
const storedMac = localStorage.getItem('hotspot_ip') 
const loginWithVoucher = async(e) => {

  e.preventDefault()
  
    try {
      setLoading(true)
      const response = await fetch('/api/login_with_hotspot_voucher', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Subdomain': subdomain,
    
        },
  
        body: JSON.stringify({
          voucher: vouchers,
          router_name: settingsformData.router_name,
          stored_mac: storedMac,
          stored_ip: storedIp, 
          // mac: mac,
          // ip: ip
        })
    
    
      });
    
    
      const newData = await response.json();
      if (response.ok) {
        setLoading(false)
        setTimeout(() => {
          setsuccess(true)
    
        }, 2000);
        
        // setPackages(newData)
        toast.success('Voucher verified successfully', {
          duration: 3000,
          position: 'top-right',
        });
        // console.log('company settings fetched', newData)
      } else {
        setLoading(false)
        toast.error('Voucher verification failed', {
          duration: 3000,
          position: 'top-right',
        });
  
        toast.error(newData.error, {
          duration: 4000,
          position: 'top-right',
        });
      }
    } catch (error) {
      setLoading(false)
    }
   
  }





const handleGetSmsProviderSettings = useCallback(
  async() => {
    


    try {
      const response = await fetch(`/api/sms_provider_settings`, {
        headers: {
          'Content-Type': 'application/json',
          'X-Subdomain': subdomain,
        },
      });

      const newData = await response.json()
      if (response.ok) {
               setProviderSms(newData[0].sms_provider)

       

      } else {
      //   if (response.status === 402) {
      //   setTimeout(() => {
      //     // navigate('/license-expired')
      //     window.location.href='/license-expired'
      //    }, 1800);
        
      // }
// if (response.status === 401) {
 
//    setTimeout(() => {
//           // navigate('/license-expired')
//           window.location.href='/signin'
//          }, 1900);
// }
      
      }
    } catch (error) {
      console.log(error)
    }
  },
  [],
)


useEffect(() => {
  handleGetSmsProviderSettings()
  
}, [handleGetSmsProviderSettings]);



const handleChangeSubscriber = (e)=> {
    const {id, value} = e.target
    setFormDataSubscriber({...formDataSubscriber, [id]: value})
  }

      const [selectedLocations, setSelectedLocations] = useState([]);
      const [editingSubscriber, setEditingSubscriber] = useState(false)
      const [openLoad, setOpenLoad] = useState(false)
      const [tableDataSubscriber, setTableDataSubscriber] = useState([])

       const [mapForm, setMapForm] = useState({
        api_key: '',

    })
      // const [loading, setloading] = useState(false)




  const [adSetingsData, setAdSetingsData] = useState({
    enabled: false,
    to_right: false,
    to_left: false,
    to_top: false,
  })




  const [adData, setAdData] = useState({
    title: '',
    description: '',
    businessName: '',
    businessType: '',
    offerText: '',
    discount: '',
    ctaText: 'Learn More',
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    textColor: '#ffffff',
    image: null,
    imagePreview: '',
    targetUrl: '',
    isActive: true,
    
    // Business Details
    contact: {
      phone: '',
      email: '',
      website: ''
    },
    location: {
      address: '',
      city: '',
      state: '',
      zipCode: '',
      coordinates: {
        lat: '',
        lng: ''
      }
    },
    hours: {
      monday: { open: '09:00', close: '17:00', closed: false },
      tuesday: { open: '09:00', close: '17:00', closed: false },
      wednesday: { open: '09:00', close: '17:00', closed: false },
      thursday: { open: '09:00', close: '17:00', closed: false },
      friday: { open: '09:00', close: '17:00', closed: false },
      saturday: { open: '10:00', close: '16:00', closed: false },
      sunday: { open: '', close: '', closed: true }
    },
    
    // Services/Products
    services: [''],
    pricing: {
      startingFrom: '',
      priceRange: '',
      currency: 'USD'
    },
    
    // Business Features
    features: [],
    rating: 0,
    testimonials: [''],
    
    schedule: {
      startDate: '',
      endDate: ''
    }
  });

  return (
    <>
    <Toaster />
    <GeneralSettingsContext.Provider  value={{settingsformData, handleChange, setFormData, isloading,
       setisloading,
     nasformData, setnasFormData,initialValueNas, welcomeMessage, setWelcomeMessage, welcome, 
     setWelcome, tableDataNas, setTableData,currentUser, setCurrentUser,
     currentUsername, currentEmail, fetchCurrentUser,setCurrentSystemAdmin,
     currentSystemAdmin, fetchCurrentSystemAdmin,formData, setFormDataSystemAdmin,
     useEmailAuthentication, setUseEmailAuthentication, usePhoneNumberAuthentication, setUsePhoneNumberAuthentication,
     loginWithPasskey, setLoginWithPasskey,handleChangeSubscriberSettings,
     subscriberSettings,setSubscriberSettings,
     handleChangeAdminSettings, adminSettings, setAdminSettings,
     templateStates, setTemplateStates,
     handleChangeHotspotVoucher, voucher, setVoucher,
     success, setsuccess, loading,loginWithVoucher,setLoading,
     selectedProvider, setSelectedProvider,smsSettingsForm, setSmsSettingsForm,
     
     companySettings, setCompanySettings,email, setEmail,

     phoneNumber, setPhoneNumber,hotspotName, setHotspotName,hotspotInfo, setHotspotInfo,
     hotspotBanner, setHotspotBanner,hotspotBannerPreview, setHotspotBannerPreview,
     totalSubscribers, setTotalSubscribers,subscribersOnline, setSubscribersOnline,
     subscribersOffline, setSubscribersOffline,selectedAccountTypeHotspot, setSelectedAccountTypeHotspot,
     hotspotMpesaSettings, setHotspotMpesaSettings,openDropDown, setOpenDropDown,
     pingStatus, setPingStatus,smsBalance, setSmsBalance,
     showMenu1, setShowMenu1, showMenu2, setShowMenu2, showMenu3, setShowMenu3,
      showMenu4, setShowMenu4, showMenu5, setShowMenu5, showMenu6, setShowMenu6,
       showMenu7, setShowMenu7, showMenu8, setShowMenu8, showMenu9, setShowMenu9,
        showMenu10, setShowMenu10, showMenu11, setShowMenu11, showMenu12, setShowMenu12,
        locationInput, setLocationInput, allLocations, setAllLocations,
        formDataGeneralSettings, setFormDataGeneralSettings,
        currentCustomer, setCurrentCustomer,fetchCurrentCustomer,
        routerName, setRouterName,openNasTable, setOpenNasTable,
        openRouterDetails, setOpenRouterDetails,providerSms, setProviderSms,
        hotspotPhoneNumber, setHotspotPhoneNumber,hotspotEmail, setHotspotEmail,
        formDataSubscriber, setFormDataSubscriber,intialValueSubscriber,handleChangeSubscriber,
        selectedLocations, setSelectedLocations,editingSubscriber, setEditingSubscriber,
        tableDataSubscriber, setTableDataSubscriber,mapForm, setMapForm,adSetingsData, setAdSetingsData,
        adData, setAdData,selectedAccountTypeSubscriber, setSelectedAccountTypeSubscriber,
        dialMpesaSettings, setDialMpesaSettings,customerProfileData,
        hotspotCustomization, setHotspotCustomization,handleChangeHotspotCustomization,
        handleChangeNasSettings, nasSettingsForm, setNasSettingsForm,
        expiry, setExpiry, expiry2, setExpiry2, condition, setCondition,
        condition2, setCondition2, status, setStatus, status2, setStatus2,
        currentHotspotPlan, setCurrentHotspotPlan, currentPPOEPlan, 
        setCurrentPPOEPlan,calculateTimeRemaining,walletBalance,
         setWalletBalance,accessPointForm,handleChanageAccessPointSettings,
         accessPointSettingsForm, setAccessPointSettingsForm,
         
          setAccessPointForm,initialValueAccessPoint,


     }}  >
    {children}
   </GeneralSettingsContext.Provider>

   </>
  )
}
export default ApplicationSettings
export const useApplicationSettings = (()=> useContext(GeneralSettingsContext))
