import { clientsClaim } from "workbox-core";

import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";

import { NavigationRoute, Route, registerRoute } from "workbox-routing";

import {
  CacheFirst,
  NetworkFirst,
  NetworkOnly,
  StaleWhileRevalidate,
} from "workbox-strategies";

import { ExpirationPlugin } from "workbox-expiration";

import { BackgroundSyncPlugin } from "workbox-background-sync";

// Remove caches created by older versions of the service worker
cleanupOutdatedCaches();

// Activate the new service worker immediately and take over open tabs
self.skipWaiting();
clientsClaim();

// Cache files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache images
const imageRoute = new Route(
  ({ request, sameOrigin }) => {
    return sameOrigin && request.destination === "image";
  },

  new CacheFirst({
    cacheName: "images",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 150,
        maxAgeSeconds: 60 * 60 * 24 * 30,
      }),
    ],
  })
);

registerRoute(imageRoute);

// Fonts and stylesheets
const staticRoute = new Route(
  ({ request, sameOrigin }) => {
    return (
      sameOrigin &&
      (request.destination === "style" || request.destination === "font")
    );
  },

  new StaleWhileRevalidate({
    cacheName: "static-assets",
  })
);

registerRoute(staticRoute);

// Background sync
const bgSyncPlugin = new BackgroundSyncPlugin("backgroundSyncQueue", {
  maxRetentionTime: 24 * 60,
});

// API reads — fresh first, cached fallback when the link drops
const apiRoute = new Route(
  ({ url, request, sameOrigin }) => {
    return sameOrigin && request.method === "GET" && url.pathname.startsWith("/api/");
  },

  new NetworkFirst({
    cacheName: "owitech-api",
    networkTimeoutSeconds: 8,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 80,
        maxAgeSeconds: 60 * 5,
      }),
    ],
  })
);

registerRoute(apiRoute);

// Navigation requests — never intercept API, ActionCable or Rails-served paths
const NAVIGATION_DENYLIST = [
  /^\/api\//,
  /^\/cable/,
  /^\/rails\//,
  /^\/assets\//,
];

const navigationRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: "navigation",
    networkTimeoutSeconds: 3,
  }),
  { denylist: NAVIGATION_DENYLIST }
);

registerRoute(navigationRoute);

// Sign-in requests
const signinTask = new Route(
  ({ request }) => {
    return request.url.includes("api/signin");
  },

  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),

  "POST"
);

registerRoute(signinTask);

// Let the page trigger an immediate activation
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});