import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";

import { NavigationRoute, Route, registerRoute } from "workbox-routing";

import {
  CacheFirst,
  NetworkFirst,
  NetworkOnly,
} from "workbox-strategies";

import { BackgroundSyncPlugin } from "workbox-background-sync";


// Remove caches created by older versions of the service worker
cleanupOutdatedCaches();


// Activate the new service worker immediately
self.skipWaiting();


// Cache files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);


// Cache images
const imageRoute = new Route(
  ({ request, sameOrigin }) => {
    return sameOrigin && request.destination === "image";
  },

  new CacheFirst({
    cacheName: "images",
  })
);

registerRoute(imageRoute);


// Background sync
const bgSyncPlugin = new BackgroundSyncPlugin("backgroundSyncQueue", {
  maxRetentionTime: 24 * 60,
});


// Navigation requests
const navigationRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: "navigation",
    networkTimeoutSeconds: 3,
  })
);

registerRoute(navigationRoute);


// Sign-in requests
const signinTask = new Route(
  ({ request }) => {
    return request.url.includes("api/signin");
  },

  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),

  "POST"
);

registerRoute(signinTask);